spring:
  main:
    web-application-type: none
    banner-mode: off

logging:
  level:
    root: info
    com.ibasco.agql: warn

version: @project.version@

bot:
  discord-bot-token: ~
  database-path: ./bot.db
  database-username: v-rising-discord-bot
  database-password: ~
  update-delay: 1m
  max-failed-attempts: 0
  max-recent-errors: 5
  max-characters-per-error: 200
