spring:
  main:
    web-application-type: none

logging:
  level:
    root: info

version: @project.version@

bot:
  discord-bot-token: ~
  database-path: ./bot.db
  database-username: v-rising-discord-bot
  database-password: ~
  update-delay: 1m
