spring:
  main:
    web-application-type: none

logging:
  level:
    root: info

bot:
  discord-bot-token: ~
  database-path: ./bot.db
  database-username: v-rising-discord-bot
  database-password: ~
  display-player-gear-level: false
