package de.darkatra.vrising.discord.clients.botcompanion.model

enum class VBlood(
    val displayName: String
) {
    FOREST_WOLF("Alpha Wolf"),
    BANDIT_STONEBREAKER("Errol the Stonebreaker"),
    BANDIT_DEADEYE_FROSTARROW("Keely the Frost Archer"),
    BANDIT_FOREMAN("Rufus the Foreman"),
    UNDEAD_BISHOPOFDEATH("Goreswine the Ravager"),
    BANDIT_STALKER("Grayson the Armourer"),
    VERMIN_DIRERAT("Putrid Rat"),
    BANDIT_DEADEYE_CHAOSARROW("Lidia the Chaos Archer"),
    BANDIT_BOMBER("Clive the Firestarter"),
    FOREST_BEAR_DIRE("Ferocious Bear"),
    POLOMA("Polora the Feywalker"),
    UNDEAD_PRIEST("Nicholaus the Fallen"),
    BANDIT_TOUROK("Quincey the Bandit King"),
    VILLAGER_TAILOR("Beatrice the Tailor"),
    VHUNTER_LEADER("Tristan the Vampire Hunter"),
    UNDEAD_LEADER("Kriig the Undead General"),
    MILITIA_NUN("Christina the Sun Priestess"),
    MILITIA_GUARD("Vincent the Frostbringer"),
    UNDEAD_INFILTRATOR("Bane the Shadowblade"),
    MILITIA_GLASSBLOWER("Grethel the Glassblower"),
    UNDEAD_BISHOPOFSHADOWS("Leandra the Shadow Priestess"),
    MILITIA_SCRIBE("Maja the Dark Savant"),
    GEOMANCER_HUMAN("Terah the Geomancer"),
    MILITIA_LONGBOWMAN_LIGHTARROW("Meredith the Bright Archer"),
    VHUNTER_JADE("Jade the Vampire Hunter"),
    MILITIA_BISHOPOFDUNLEY("Raziel the Shepherd"),
    WENDIGO("Frostmaw the Mountain Terror"),
    MILITIA_LEADER("Octavian the Militia Captain"),
    GLOOMROT_VOLTAGE("Domina the Blade Dancer"),
    GLOOMROT_PURIFIER("Angram the Purifier"),
    GLOOMROT_IVA("Ziva the Engineer"),
    SPIDER_QUEEN("Ungora the Spider Queen"),
    VILLAGER_CURSEDWANDERER("The Old Wanderer"),
    UNDEAD_ZEALOUSCULTIST("Foulrot the Soultaker"),
    WEREWOLFCHIEFTAIN("Willfred the Werewolf Chief"),
    CURSED_TOADKING("The Duke of Balaton"),
    UNDEAD_CURSEDSMITH("Cyril the Cursed Smith"),
    CHURCHOFLIGHT_OVERSEER("Sir Magnus the Overseer"),
    ARCHMAGE("Mairwyn the Elementalist"),
    CHURCHOFLIGHT_SOMMELIER("Baron du Bouchon the Sommelier"),
    HARPY_MATRIARCH("Morian the Stormwing Matriarch"),
    WINTER_YETI("Terrorclaw the Ogre"),
    CHURCHOFLIGHT_CARDINAL("Azariel the Sunbringer"),
    GLOOMROT_THEPROFESSOR("Henry Blackbrew the Doctor"),
    CURSED_WITCH("Matka the Curse Weaver"),
    GLOOMROT_RAILGUNSERGEANT("Voltatia the Power Master"),
    BATVAMPIRE("Nightmarshal Styx the Sunderer"),
    CHURCHOFLIGHT_PALADIN("Solarus the Immaculate"),
    GLOOMROT_MONSTER("Adam the Firstborn"),
    CURSED_MOUNTAINBEAST("Gorecrusher the Behemoth"),
    MANTICORE("The Winged Horror"),
    BANDIT_FISHERMAN("Finn"),
    ICE_RANGER("Elena"),
    BLOOD_KNIGHT("Valencia"),
    HIGH_LORD("Cassius"),
    DRACULA("Dracula"),
    VHUNTER("Simon Belmont")
}
