plugins:
  - jekyll-github-metadata
  - jekyll-mentions
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-remote-theme
  - jekyll-default-layout
  - jekyll-titles-from-headings
  - jekyll-relative-links

remote_theme: just-the-docs/just-the-docs@v0.8.2

color_scheme: my-dark
title: V Rising Discord Bot
description: The documentation for the V Rising Discord Bot.

gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/DarkAtra/v-rising-discord-bot"
gh_edit_branch: "main"
gh_edit_view_mode: "edit"

back_to_top: true
back_to_top_text: "Back to top"

heading_anchors: true

enable_copy_code_button: true

aux_links:
  "Join our Discord":
    - "https://discord.gg/KcMcYKa6Nt"

callouts:
  warning:
    title: Warning
    color: red
  note:
    title: Note
    color: purple
